- name: Install Docker
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - docker.io

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
